#!/bin/sh 
EGREPARG=$1
shift
aptconfig=/etc/apt/apt.conf.SS
if [ "$1" = "--apt-config" ]; then
	aptconfig="$2"
	shift;
	shift;
fi
hshB="hsh --apt-config=$aptconfig --mountpoints=/proc"
mkdir success failure
for i in "$@"; do
    if rpmquery --requires -p $i | egrep "$EGREPARG" >/dev/null; then 
	echo rebuilding $i
	if $hshB $i > hsh.log 2>&1 ; then
	    mv hsh.log success/`basename $i`.log
	else 
	    mv hsh.log failure/`basename $i`.log
	    echo FAILED: $i
	fi
    fi
    rm -f ~/hasher/repo/SRPMS.hasher/*.src.rpm ~/hasher/repo/x86_64/RPMS.hasher/*.rpm
done
