#!/bin/sh 
EGREPARG=$1
shift
aptconfig=/etc/apt/apt.conf.SS
if [ "$1" = "--apt-config" ]; then
	aptconfig="$2"
	shift;
	shift;
fi
number=1
hasherdir=$TMPDIR/hasher$number
if ! [ -e $hasherdir ]; then
    mkdir -p $hasherdir/chroot
    chgrp -R `whoami`_a$number $hasherdir/chroot
fi
hshB="hsh --apt-config=$aptconfig --mountpoints=/proc --number=$number $hasherdir"
mkdir success failure
for i in "$@"; do
    if rpmquery --requires -p $i | egrep "$EGREPARG" >/dev/null; then 
	echo rebuilding $i
	#echo $hshB $i
	if $hshB $i > hsh.log 2>&1 ; then
	    mv hsh.log success/`basename $i`.log
	else 
	    mv hsh.log failure/`basename $i`.log
	    echo FAILED: $i
	fi
    fi
    rm -f $hasherdir/repo/SRPMS.hasher/*.src.rpm $hasherdir/repo/x86_64/RPMS.hasher/*.rpm
done
