#!/bin/sh

PREFIX=/var/ftp/pub/Linux/fedora/linux/development/rawhide/
NAME=java-fc-packages
DEST=`pwd`

[ -n "$1" ] && PREFIX="$1" && shift;
[ -n "$1" ] && NAME="$1" && shift;

JAVA_PATTERN='/usr/(share/java|share/netbeans|share/eclipse|lib/eclipse|lib64/eclipse)'

[ -d $PREFIX/source/SRPMS ] && SOURCE_RPM_PATH="$PREFIX/source/SRPMS"
[ -z "$SOURCE_RPM_PATH" ] && exit 2;

get_arch_rpmdir()
{
    ARCH_RPMDIR=
    [ -d "$PREFIX/files/$ARCH/RPMS" ] && ARCH_RPMDIR="$PREFIX/files/$ARCH/RPMS/" && return
    [ -d "$PREFIX/$ARCH/os/Packages" ] && ARCH_RPMDIR="$PREFIX/$ARCH/os/Packages/" && return
}

list_java_src_rpm_names()
{
    local ARCH
    ARCH=$1
    for i in `find . -name '*.'$ARCH'.rpm'`; do 
    if rpmquery -l -p $i | egrep "$JAVA_PATTERN" >/dev/null; then 
	SRCRPMNAME=`rpmquery --queryformat '%{SOURCERPM}\n' -p $i`;
	SRCNAME=`rpmquery --queryformat '%{NAME}\n' -p $SOURCE_RPM_PATH/?/$SRCRPMNAME`;
	if [ -z "$ACL" ] || grep '^'$SRCNAME "$ACL" | egrep "$ACLPATTERN" >/dev/null; then
	    echo $SRCNAME
	fi; 
    fi; 
    done  | sort -u > $DEST/$NAME.$ARCH.src
}

ARCH=x86_64
get_arch_rpmdir
pushd $ARCH_RPMDIR
list_java_src_rpm_names $ARCH
list_java_src_rpm_names noarch
popd

grep -v -E '^(gcc|libdb|subversion|fedora-ds-)' $DEST/$NAME.$ARCH.src | sort -u > $DEST/$NAME.$ARCH.src.0
mv $DEST/$NAME.$ARCH.src.0 $DEST/$NAME.$ARCH.src

sort -u $DEST/$NAME.$ARCH.src $DEST/$NAME.noarch.src > $NAME.src
