#!/bin/sh

PREFIX=/var/ftp/pub/Linux/jpackage
NAME=java-jpp-packages
DEST=`pwd`

[ -n "$1" ] && PREFIX="$1" && shift;
[ -n "$1" ] && NAME="$1" && shift;

rpmquery --queryformat '%{NAME}\n' -p `find $PREFIX/5.0 $PREFIX/6.0 -type f -name '*.src.rpm'` | \
sort -u > $DEST/$NAME.src


