#!/bin/sh

PREFIX=/var/ftp/pub/Linux/ALT/Sisyphus

[ -n "$1" ] && PREFIX="$1" && shift;

DEST=`pwd`

pushd $PREFIX/files/noarch/RPMS/
for i in *.rpm; do if rpmquery -l -p $i | grep /usr/share/java >/dev/null; then  rpmquery --queryformat '%{NAME}\n' -p ../../SRPMS/`rpmquery --queryformat '%{SOURCERPM}\n' -p $i` ; fi; done  | sort -u > $DEST/java-alt-packages.noarch.src
popd
echo jpackage-1.4-compat >> $DEST/java-alt-packages.noarch.src
echo jpackage-1.5-compat >> $DEST/java-alt-packages.noarch.src
pushd $PREFIX/files/i586/RPMS/
for i in *.rpm; do if rpmquery -l -p $i | grep /usr/share/java >/dev/null; then  rpmquery --queryformat '%{NAME}\n' -p ../../SRPMS/`rpmquery --queryformat '%{SOURCERPM}\n' -p $i` ; fi; done | grep -v -E '^(gcc|libdb|subversion)' | sort -u > $DEST/java-alt-packages.i586.src
popd
for i in `sort -u ./java-alt-packages.i586.src ./java-alt-packages.noarch.src`; do grep "^$i" $PREFIX/files/list/list.src.classic ; done | sort -u > $DEST/java-alt-packages.owners

