#!/usr/bin/perl -w

require 'set_osgi.pl';
require 'set_manual_no_dereference.pl';
# not tested, just in case
require 'set_dos2unix_scripts.pl';

push @SPECHOOKS, sub {
    my ($jpp, $alt) = @_;

    # ALT Compat provides
    if (not $jpp->get_section('package','')->match_body(qr'Provides: xalan-j = ')) {
	$jpp->get_section('package','')->push_body('Provides: xalan-j = %{name}-%{version}'."\n");
	$jpp->get_section('package','')->push_body('Obsoletes: xalan-j <= 2.7.0-alt3'."\n");
    }
};

__END__

    # jpp compat symlinks
    $jpp->get_section('install')->push_body('# jpp compat
ln -s %{name}-serializer.jar $RPM_BUILD_ROOT/%{_javadir}/serializer.jar
ln -s %{name}.jar $RPM_BUILD_ROOT/%{_javadir}/xalan.jar'."\n");
    $jpp->get_section('files','')->unshift_body('%{_javadir}/xalan.jar'."\n");
    $jpp->get_section('files','')->unshift_body('%{_javadir}/serializer.jar'."\n");

    # repolib
    $jpp->copy_to_sources('xalan-j2-2.7.0-component-info.xml');
    $jpp->get_section('package','')->push_body('# jpackage compat
# autogenerated from fedora alternatives
#Provides:       jaxp_transform_impl
Source11:        xalan-j2-2.7.0-component-info.xml

'."\n");

    $jpp->get_section('install')->push_body(q!
#from fedora
#install -d $RPM_BUILD_ROOT/%_altdir; cat >$RPM_BUILD_ROOT/%_altdir/jaxp_transform_impl_%{name}<<EOF
#%{_javadir}/jaxp_transform_impl.jar	%{_javadir}/%{name}.jar	30
#EOF
install -d $RPM_BUILD_ROOT/%_altdir; cat >$RPM_BUILD_ROOT/%_altdir/jaxp_transform_impl_%{name}-xsltc<<EOF
%{_javadir}/jaxp_transform_impl.jar	%{_javadir}/xsltc.jar	10
EOF
!."\n");

# in fedora
#    $jpp->get_section('files','')->push_body('%_altdir/jaxp_transform_impl_%{name}'."\n");
    $jpp->get_section('files','xsltc')->push_body('%_altdir/jaxp_transform_impl_%{name}-xsltc'."\n");




